name: Test build and package QubesOS RPMs

on:
  push:
    branches:
      - 'aem*'
    tags:
      - '*'
  pull_request_target:
    branches: # this is to avoid running the workflow twice in a PR
      - 'aem*'

jobs:
  qubes-dom0-package:
    uses: TrenchBoot/.github/.github/workflows/qubes-dom0-package.yml@master
    with:
      base-commit: 'cbb35e72802f3a285c382a995ef647b59e5caf2f'
      patch-start: 1300
      qubes-component: 'vmm-xen'
      spec-pattern: '/^Patch1202:/'
