name: Rebase and build the last successful automatic rebase of aem-next branch

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: >
          Set this input to do a dry run without building the packages to test
          the rebase.
        required: false
        type: boolean
        default: false
  schedule:
    - cron: '0 0 * * 6'

concurrency:
  group: automatic-rebase

jobs:
  run:
    uses: TrenchBoot/.github/.github/workflows/qubes-derivative-rebase-and-publish.yml@v1
    secrets:
      rebase-token:      ${{ secrets.TRENCHBOOT_REBASE_TOKEN }}
      woodpecker-token:  ${{ secrets.WOODPECKER_TOKEN }}
    with:
      source-repo:         TrenchBoot/xen
      downstream-branch:   aem-next
      pkg-repo:            QubesOS/qubes-vmm-xen
      upstream-url:        https://xenbits.xenproject.org/git-http/xen.git
      upstream-tag-format: 'RELEASE-%s'
      pkg-spec-in:         xen.spec.in
      qubes-component:     vmm-xen
      pkg-file-renames: |
        config:config-qubesos
      dry-run: ${{ inputs.dry_run == true }}
